services:
    app:
        build: .
        container_name: laravel_app
        ports:
            - "9000:80" # Access application on port 9000
        volumes:
            - .:/var/www/html
            - storage_data:/var/www/html/storage
            - cache_data:/var/www/html/bootstrap/cache
        networks:
            - app_network
        environment:
             - APP_ENV=local
             - APP_DEBUG=true
             - DB_HOST=db
             - DB_PORT=3306
             - DB_DATABASE=posts_api
             - DB_USERNAME=solikhin
             - DB_PASSWORD=solikhin
        depends_on:
            db:
                condition: service_healthy
        mem_limit: "2G"
        cpus: "1"

    db:
        image: mysql:8.0
        container_name: mysql_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: posts_api
            MYSQL_ROOT_PASSWORD: solikhin
            MYSQL_USER: solikhin
            MYSQL_PASSWORD: solikhin
        ports:
            - "3307:3306" # MySQL accessible on port 3307
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - app_network
        mem_limit: "2G"
        cpus: "1"
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            retries: 5

    frontend:
        build:
            context: ../front-end-nextjs  
            dockerfile: Dockerfile
        container_name: nextjs_frontend
        ports:
            - "3000:3000"  # Next.js accessible on port 3000
        networks:
            - app_network
        depends_on:
            - app
        volumes:
            - ../front-end-nextjs:/app
            - /app/node_modules
        environment:
            - VITE_API_URL=http://localhost:9000

volumes:
    db_data:
    storage_data:
    cache_data:

networks:
    app_network:
        driver: bridge
